version: '3'
services:
  mysql:
    image: mariadb:latest
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
  mailcatcher:
     image: schickling/mailcatcher
     restart: always
     ports:
       - "1025:1025"
       - "1080:1080"
     environment:
       MAILCATCHER_PORT: 1025
  memcached:
    image: memcached:latest
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    ports:
      - "9200:9200"
    volumes:
      - "./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./config/elasticsearch/plugins:/usr/share/elasticsearch/plugins"
  phpfpm:
    image: 10up/phpfpm
    depends_on:
      - mysql
      - memcached
      - elasticsearch
    volumes:
      - "./www:/var/www"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "./logs/xdebug:/var/log/xdebug"
    restart: always
    extra_hosts:
      - "docker-local.dev:172.18.0.1"
  nginx:
    depends_on:
      - phpfpm
    ports:
      - "80:80"
      - "443:443"
    image: nginx:latest
    links:
      - phpfpm
    volumes:
      - "./www:/var/www"
      - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./config/nginx/common:/etc/nginx/common"
      - "./config/nginx/sites-available:/etc/nginx/sites-available"
      - "./config/nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "./config/certs:/etc/nginx/certs"
      - "./logs/nginx:/var/log/nginx"
    restart: always
